language: python
services:
- mysql
python:
- 2.7
install:
- pip install -r Web/requeriments.txt
before_script:
- mysql -e 'create database facefinder;'
- cp Web/FaceFinder/travis_settings.py Web/FaceFinder/settings.py
- python Web/manage.py migrate
script:
- python Web/manage.py test
