# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import slave.models


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apelidos')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('picture', models.ImageField(upload_to=slave.models.pictures_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='twitteritem',
            name='account',
            field=models.CharField(max_length=200, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='twitteritem',
            name='imageUrl',
            field=models.CharField(max_length=600, verbose_name='Url da Imaxe'),
        ),
        migrations.AlterField(
            model_name='twitteritem',
            name='occurrence',
            field=models.FloatField(verbose_name='Acerto'),
        ),
        migrations.AlterField(
            model_name='twitteritem',
            name='tweetUrl',
            field=models.CharField(max_length=600, verbose_name='Url do Tweet'),
        ),
        migrations.AddField(
            model_name='twitteritem',
            name='people',
            field=models.ManyToManyField(blank=True, to='slave.Person'),
        ),
    ]
