# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import slave.models


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0002_auto_20160412_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photos',
            field=models.ManyToManyField(blank=True, to='slave.TwitterItem'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(upload_to=slave.models.pictures_directory_path, verbose_name='Foto'),
        ),
    ]
